swagger: "2.0"

info:
  title: "Review classification API"
  description: "A simple api that predicts if a Zomato review is carrying positive or negative sentiment."
  version: "1.0"

paths:
  /predict:
    post:
      consumes:
        - application/json
      parameters: 
        - in: body
          name: text
          description: Review to be classified. 
          schema:
            type: "string"
      responses:
        '200':
          description: OK
          schema: 
            type: "string"
          examples:
            Sentiment:
              Sentiment:
                'positive'
            
